Repository azu/request-filtering-agent, pull requests merged in 2023-10, with the labels that each got.

#16 fix: support Node.js 20
  .github/workflows/ci.yml
  README.md
  src/request-filtering-agent.ts
  test/request-filtering-agent.test.ts
  tsconfig.json
Labels: Type: Bug, Type: Breaking Change

#17 BREAKING CHANGE: Drop Node.js 12, 14, 16 support
  package.json
  test/request-filtering-agent.test.ts
  tsconfig.json
  yarn.lock
Labels: Type: Breaking Change

#20 Use lookup func instead of listener
  src/request-filtering-agent.ts
Labels: Type: Bug

#22 Failing tests for #19
  test/request-filtering-agent.test.ts
Labels: Type: Testing
